on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build & Deploy
        run: |
          npm install
          npm run compile:evm

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: build/