on:
  push:
    branches:
      - 'main'

jobs:
  generate-candidate-build:
    name: "Push: main"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install -g truffle
          npm install

      - name: Test
        run: |
          npm run test:evm

      - name: Compile
        run: |
          npm run compile:evm

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: build/